apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secret
  namespace: devsecops
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production-k8s-secret-key-12345"
  DB_PASSWORD: "Komanda"
  TMDB_API_KEY: "your-tmdb-api-key-here"
