apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_DB: ZGphbmdvX2Ri
  POSTGRES_USER: ZGphbmdvX3VzZXI=
  POSTGRES_PASSWORD: ZGphbmdvX3Bhc3NfQ2hhbmdlTWU=
  SECRET_KEY: azN3emstdXhnYiYxYmE2Z28zQHQkOHMhaDUhZClyanF2MXlvPW5kMSZvNjcpbSt1PWo=
