apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_NAME: ZGphbmdvX2Ri
  DB_USER: ZGphbmdvX3VzZXI=
  DB_PASSWORD: ZGphbmdvX3Bhc3NfQ2hhbmdlTWU=
  SECRET_KEY: azN3emstdXhnYiYxYmE2Z28zQHQkOHMhaDUhZClyanF2MXlvPW5kMSZvNjcpbSt1PWo=
