apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_NAME: bXlkYg==
  DB_USER: bXl1c2Vy
  DB_PASSWORD: bXlwYXNzd29yZA==
  SECRET_KEY: azN3emstdXhnYiYxYmE2Z28zQHQkOHMhaDUhZClyanF2MXlvPW5kMSZvNjcpbSt1PWo=
